#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Example: PNG Generation Daemon

This example demonstrates how to use the PNGGenerationDaemon to monitor
processed NetCDF files and automatically generate PNG field plots and COLMAX.
"""

import asyncio
import os
from datetime import datetime, timezone
from pathlib import Path

from radarlib import config
from radarlib.io.ftp import PNGGenerationDaemon, PNGGenerationDaemonConfig


def example_basic_png_daemon():
    """
    Example: Basic PNG generation daemon setup.

    This daemon will monitor NetCDF files generated by the ProcessingDaemon
    and automatically generate PNG plots for all fields including COLMAX.
    """
    print("=" * 60)
    print("Basic PNG Generation Daemon Example")
    print("=" * 60)

    # Define volume types - same as used in download and processing daemons
    volume_types = {
        "0315": {
            "01": ["DBZH", "DBZV", "ZDR", "RHOHV", "PHIDP", "KDP"],
            "02": ["VRAD", "WRAD"],
        },
    }

    radar_name = "RMA1"
    base_path = Path(os.path.join(config.ROOT_RADAR_FILES_PATH, radar_name))

    daemon_config = PNGGenerationDaemonConfig(
        local_netcdf_dir=base_path / "netcdf",  # Where NetCDF files are located
        local_png_dir=base_path / "png",  # Where to save PNG files
        state_db=base_path / "state.db",  # Same database as other daemons
        volume_types=volume_types,
        radar_name=radar_name,
        poll_interval=30,  # Check every 30 seconds
        max_concurrent_processing=2,  # Process 2 volumes at a time
        add_colmax=True,  # Generate COLMAX field
    )

    daemon = PNGGenerationDaemon(daemon_config)

    print("\nDaemon Configuration:")
    print(f"  Radar: {daemon_config.radar_name}")
    print(f"  NetCDF Dir: {daemon_config.local_netcdf_dir}")
    print(f"  PNG Dir: {daemon_config.local_png_dir}")
    print(f"  State DB: {daemon_config.state_db}")
    print(f"  Poll Interval: {daemon_config.poll_interval}s")
    print(f"  Add COLMAX: {daemon_config.add_colmax}")

    print("\nStarting PNG generation daemon...")
    print("Press Ctrl+C to stop\n")
    print("-" * 60)

    try:
        asyncio.run(daemon.run())
    except KeyboardInterrupt:
        print("\nDaemon stopped by user")

    stats = daemon.get_stats()
    print("\n" + "=" * 60)
    print("Daemon Statistics:")
    print(f"  Volumes processed: {stats['volumes_processed']}")
    print(f"  Volumes failed: {stats['volumes_failed']}")
    print(f"  Pending volumes: {stats['pending_volumes']}")
    print(f"  Completed volumes: {stats['completed_volumes']}")
    print("=" * 60)


def example_combined_pipeline():
    """
    Example: Run all three daemons together.

    This shows how to run download, processing, and PNG generation daemons
    concurrently to create a complete pipeline from FTP download to PNG output.
    """
    print("=" * 60)
    print("Combined Pipeline Example (Download + Processing + PNG)")
    print("=" * 60)

    from radarlib.io.ftp import ContinuousDaemon, ContinuousDaemonConfig, ProcessingDaemon, ProcessingDaemonConfig

    volume_types = {
        "0315": {
            "01": ["DBZH", "DBZV", "ZDR", "RHOHV", "PHIDP", "KDP"],
            "02": ["VRAD", "WRAD"],
        },
    }

    radar_name = "RMA1"
    base_path = Path(os.path.join(config.ROOT_RADAR_FILES_PATH, radar_name))

    # Configure download daemon
    download_config = ContinuousDaemonConfig(
        host=config.FTP_HOST,
        username=config.FTP_USER,
        password=config.FTP_PASS,
        remote_base_path="/L2",
        radar_name=radar_name,
        local_bufr_dir=base_path / "bufr",
        state_db=base_path / "state.db",
        start_date=datetime(2025, 11, 24, tzinfo=timezone.utc),
        poll_interval=60,
        vol_types=volume_types,
    )

    # Configure processing daemon
    processing_config = ProcessingDaemonConfig(
        local_bufr_dir=base_path / "bufr",
        local_netcdf_dir=base_path / "netcdf",
        state_db=base_path / "state.db",
        volume_types=volume_types,
        radar_name=radar_name,
        poll_interval=30,
    )

    # Configure PNG generation daemon
    png_config = PNGGenerationDaemonConfig(
        local_netcdf_dir=base_path / "netcdf",
        local_png_dir=base_path / "png",
        state_db=base_path / "state.db",
        volume_types=volume_types,
        radar_name=radar_name,
        poll_interval=30,
        add_colmax=True,
    )

    download_daemon = ContinuousDaemon(download_config)
    processing_daemon = ProcessingDaemon(processing_config)
    png_daemon = PNGGenerationDaemon(png_config)

    async def run_all_daemons():
        """Run all three daemons concurrently."""
        print("\nStarting all daemons concurrently...")
        print("  - Download daemon: monitoring FTP for new BUFR files")
        print("  - Processing daemon: processing complete volumes to NetCDF")
        print("  - PNG daemon: generating PNG plots from NetCDF files")
        print("\nPress Ctrl+C to stop all daemons\n")
        print("-" * 60)

        tasks = [
            asyncio.create_task(download_daemon.run_service()),
            asyncio.create_task(processing_daemon.run()),
            asyncio.create_task(png_daemon.run()),
        ]

        try:
            await asyncio.gather(*tasks)
        except asyncio.CancelledError:
            print("\nAll daemons cancelled")

    try:
        asyncio.run(run_all_daemons())
    except KeyboardInterrupt:
        print("\nDaemons stopped by user")

    # Show statistics from all daemons
    download_stats = download_daemon.get_stats()
    processing_stats = processing_daemon.get_stats()
    png_stats = png_daemon.get_stats()

    print("\n" + "=" * 60)
    print("Download Daemon Statistics:")
    print(f"  Total files downloaded: {download_stats['total_downloaded']}")

    print("\nProcessing Daemon Statistics:")
    print(f"  Volumes processed: {processing_stats['volumes_processed']}")
    print(f"  Volumes failed: {processing_stats['volumes_failed']}")

    print("\nPNG Generation Daemon Statistics:")
    print(f"  Volumes processed: {png_stats['volumes_processed']}")
    print(f"  Volumes failed: {png_stats['volumes_failed']}")
    print("=" * 60)


def example_check_png_status():
    """
    Example: Check PNG generation status.

    Shows how to query the database to see which volumes have been
    processed for PNG generation and which are pending.
    """
    print("=" * 60)
    print("PNG Generation Status Example")
    print("=" * 60)

    from radarlib.io.ftp import SQLiteStateTracker

    radar_name = "RMA1"
    db_path = Path(os.path.join(config.ROOT_RADAR_FILES_PATH, radar_name, "state.db"))

    if not db_path.exists():
        print(f"\nNo database found at {db_path}")
        print("Run the daemons first to create the database.")
        return

    tracker = SQLiteStateTracker(db_path)

    print(f"\nDatabase: {db_path}")

    # Get volumes by PNG status
    pending = tracker.get_volumes_by_png_status("pending")
    processing = tracker.get_volumes_by_png_status("processing")
    completed = tracker.get_volumes_by_png_status("completed")
    failed = tracker.get_volumes_by_png_status("failed")

    print("\nPNG Generation Status Summary:")
    print(f"  Pending: {len(pending)}")
    print(f"  Processing: {len(processing)}")
    print(f"  Completed: {len(completed)}")
    print(f"  Failed: {len(failed)}")

    # Show volumes ready for PNG generation
    ready = tracker.get_volumes_for_png_generation()
    print(f"\nVolumes ready for PNG generation: {len(ready)}")

    if ready:
        print("\nNext volumes to process:")
        for i, vol in enumerate(ready[:5], 1):
            print(f"\n  {i}. {vol['volume_id']}")
            print(f"     NetCDF: {vol['netcdf_path']}")
            print(f"     Complete: {vol['is_complete'] == 1}")
            print(f"     PNG Status: {vol['png_status']}")

    # Show completed PNG generations
    if completed:
        print("\nRecently completed PNG generations (last 5):")
        for i, vol in enumerate(completed[-5:], 1):
            print(f"\n  {i}. {vol['volume_id']}")
            print(f"     Generated: {vol['png_generated_at']}")

    # Show failed PNG generations
    if failed:
        print("\nFailed PNG generations:")
        for i, vol in enumerate(failed, 1):
            print(f"\n  {i}. {vol['volume_id']}")
            print(f"     Error: {vol['png_error_message']}")

    tracker.close()
    print("\n" + "=" * 60)


def example_with_daemon_manager():
    """
    Example: Use DaemonManager to run all daemons.

    This shows the easiest way to run all three daemons together
    using the DaemonManager.
    """
    print("=" * 60)
    print("Daemon Manager Example (All Three Daemons)")
    print("=" * 60)

    from radarlib.io.ftp.daemon_manager import DaemonManager, DaemonManagerConfig

    volume_types = {
        "0315": {
            "01": ["DBZH", "DBZV", "ZDR", "RHOHV", "PHIDP", "KDP"],
            "02": ["VRAD", "WRAD"],
        },
    }

    radar_name = "RMA1"
    base_path = Path(os.path.join(config.ROOT_RADAR_FILES_PATH, radar_name))

    # Create manager configuration with all daemons enabled
    manager_config = DaemonManagerConfig(
        radar_name=radar_name,
        base_path=base_path,
        ftp_host=config.FTP_HOST,
        ftp_user=config.FTP_USER,
        ftp_password=config.FTP_PASS,
        ftp_base_path="/L2",
        volume_types=volume_types,
        start_date=datetime(2025, 11, 24, tzinfo=timezone.utc),
        download_poll_interval=60,
        processing_poll_interval=30,
        png_poll_interval=30,
        enable_download_daemon=True,
        enable_processing_daemon=True,
        enable_png_daemon=True,
        add_colmax=True,
    )

    manager = DaemonManager(manager_config)

    print("\nStarting daemon manager with all three daemons...")
    print("  - Download, Processing, and PNG Generation daemons will start")
    print("  Press Ctrl+C to stop all daemons\n")

    try:
        asyncio.run(manager.start())
    except KeyboardInterrupt:
        print("\n\nStopping daemons...")
        manager.stop()
        print("All daemons stopped")

    # Show final status
    status = manager.get_status()
    print("\n" + "=" * 60)
    print("Final Status:")
    print(f"  Radar: {status['radar_code']}")

    print("\n  Download daemon:")
    print(f"    Enabled: {status['download_daemon']['enabled']}")
    if status["download_daemon"]["stats"]:
        print(f"    Files downloaded: {status['download_daemon']['stats']['total_downloaded']}")

    print("\n  Processing daemon:")
    print(f"    Enabled: {status['processing_daemon']['enabled']}")
    if status["processing_daemon"]["stats"]:
        print(f"    Volumes processed: {status['processing_daemon']['stats']['volumes_processed']}")

    print("\n  PNG daemon:")
    print(f"    Enabled: {status['png_daemon']['enabled']}")
    if status["png_daemon"]["stats"]:
        print(f"    Volumes processed: {status['png_daemon']['stats']['volumes_processed']}")
    print("=" * 60)


if __name__ == "__main__":
    # Uncomment the example you want to run:

    # Basic PNG generation daemon
    example_basic_png_daemon()

    # Combined pipeline with all three daemons
    # example_combined_pipeline()

    # Check PNG generation status
    # example_check_png_status()

    # Use daemon manager for all daemons
    # example_with_daemon_manager()
